targets:
  $default:
    builders:
      transfer_bean_generator|transfer_bean_generator:
        enabled: true

builders:
  transfer_bean_generator:
    import: "package:cl_datahub_common/builder.dart"
    builder_factories: ["transferBeanGenerator"]
    build_extensions: {".dart": [".dto.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  transfer_superclass_generator:
    import: "package:cl_datahub_common/builder.dart"
    builder_factories: ["transferSuperclassGenerator"]
    build_extensions: {".dart": [".dts.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]