name: cl_datahub_common
description: Shared code for datahub and appbase.
version: 1.0.0
homepage: https://www.corelightservices.com
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  boost:
    git:
      url: https://github.com/christian-thiele/dart_boost
      ref: dev

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
