name: cl_datahub_common
description: Shared code for cl_datahub and cl_appbase.
version: 0.4.1
homepage: https://www.corelightservices.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^3.3.1
  boost: ^1.4.0
  build: ^2.2.1
  source_gen: ^1.2.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
