name: cl_datahub_common
description: Shared code for cl_datahub and cl_appbase.
version: 0.5.0
homepage: https://www.corelightservices.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  boost: ^1.4.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
