targets:
  $default:
    builders:
      cl_datahub:config_generator:
        enabled: true
        generate_for:
          - test/**
      cl_datahub:transfer_bean_generator:
        enabled: true
        generate_for:
          - test/**
      cl_datahub:transfer_superclass_generator:
        enabled: true
        generate_for:
          - test/**
      cl_datahub:copy_with_extension_generator:
        enabled: true
        generate_for:
          - test/**

builders:
  config_generator:
    import: "package:cl_datahub/builder.dart"
    builder_factories: ["configGenerator"]
    build_extensions: {".dart": [".config.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  transfer_bean_generator:
    import: "package:cl_datahub/builder.dart"
    builder_factories: ["transferBeanGenerator"]
    build_extensions: {".dart": [".dto.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  transfer_superclass_generator:
    import: "package:cl_datahub/builder.dart"
    builder_factories: ["transferSuperclassGenerator"]
    build_extensions: {".dart": [".dts.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  copy_with_extension_generator:
    import: "package:cl_datahub/builder.dart"
    builder_factories: ["copyWithExtensionGenerator"]
    build_extensions: {".dart": [".cwe.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]