name: cl_datahub
description: A Framework for creating Web APIs.
version: 0.10.0
homepage: https://www.corelightservices.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  boost: ^1.5.2
  postgres: ^2.4.3
  uuid: ^3.0.1
  cl_datahub_common: 0.7.0
  path: ^1.8.0
  intl: ^0.17.0
  source_gen: ^1.2.2
  analyzer: ^4.0.0
  build: ^2.3.0
  build_runner: ^2.1.10
  dart_amqp: ^0.2.1
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.21.1

