name: datahub
description: DataHub is a Cloud Development Ecosystem aiming to bring the power of Dart into the Cloud.
version: 0.16.0-dev.3
homepage: https://datahubproject.net/

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  datahub:

dependencies:
  args: ^2.3.1
  boost: ^1.8.0
  dart_amqp: ^0.2.1
  http: ^0.13.5
  http2: ^2.0.0
  intl: ^0.17.0
  path: ^1.8.0
  postgres: ^2.4.3
  rxdart: ^0.27.5
  uuid: ^3.0.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.0
  datahub_codegen: ^0.15.0
  pedantic: ^1.11.0
  test: ^1.21.1

