name: cl_datahub
description: A Framework for creating Web APIs.
version: 0.2.3
homepage: https://www.corelightservices.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  boost: ^1.4.0
  postgres: ^2.3.0-null-safety.2
  uuid: ^3.0.1
  cl_datahub_common: 0.2.1
  path: ^1.8.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
