name: cl_datahub
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.corelightservices.com

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  boost: ^0.0.5-nullsafety
  postgres: ^2.2.0
  uuid: 2.2.2


dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
