name: datahub_workspace
publish_to: none

environment:
  sdk: ^3.10.0

dev_dependencies:
  datahub_codegen: ^0.18.0-dev.3
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.7.1
  melos: ^7.1.1

workspace:
  - packages/boost
  - packages/datahub
  - packages/datahub_aperture
  - packages/datahub_aperture_frontend
  - packages/datahub_codegen
  - packages/datahub_postgres

melos:
  scripts:
    analyze:
      exec: dart analyze .

    build_runner:
      exec: dart run build_runner build

    test:
      exec: dart test .
      packageFilters:
        flutter: false
