name: datahub
description: A dart ecosystem for developing cloud native microservices.
version: 0.13.1
homepage: https://datahubproject.net/

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  datahub:

dependencies:
  boost: ^1.7.0
  postgres: ^2.4.3
  uuid: ^3.0.1
  path: ^1.8.0
  intl: ^0.17.0
  dart_amqp: ^0.2.1
  yaml: ^3.1.0
  args: ^2.3.1

dev_dependencies:
  datahub_codegen: ^0.13.1
  pedantic: ^1.11.0
  test: ^1.21.1

