name: cl_datahub
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.corelightservices.com
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  boost: ^0.0.9-nullsafety
  postgres: ^2.3.0-null-safety.2
  uuid: ^3.0.1
  cl_datahub_common:
    path: datahub_common


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
