name: datahub
description: DataHub is a Cloud Development Ecosystem aiming to bring the power of Dart into the Cloud.
version: 0.17.0-dev.1
homepage: https://datahubproject.net/

environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  datahub:

dependencies:
  args: ^2.3.1
  boost: ^1.8.8
  dart_amqp: ^0.2.3
  http: ^0.13.5
  http2: ^2.0.0
  intl: ^0.17.0
  path: ^1.8.2
  pointycastle: ^3.6.2
  postgres: ^2.5.0
  rxdart: ^0.27.5
  uuid: ^3.0.6
  yaml: ^3.1.1
  test: ^1.21.6
  minio: ^3.5.0

dev_dependencies:
  build_runner: ^2.2.0
  datahub_codegen: ^0.16.2
  pedantic: ^1.11.0

false_secrets:
  - test/resource_hub/localhost.crt
  - test/resource_hub/localhost.key

