name: datahub_workspace
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  datahub_codegen: 0.18.0-dev.1
  lints: ^6.0.0
  test: ^1.21.6
  build_runner: ^2.7.0
  melos: ^7.1.0

workspace:
  - packages/datahub
  - packages/datahub_codegen
  - packages/datahub_postgres

melos:
  scripts:
    analyze:
      exec: dart analyze .
