name: cl_datahub
description: A Framework for creating Web APIs.
version: 0.4.0
homepage: https://www.corelightservices.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  boost: ^1.5.0
  postgres: ^2.4.3
  uuid: ^3.0.1
  cl_datahub_common:
    path: datahub_common
  path: ^1.8.1
  intl: ^0.17.0
  source_gen: ^1.2.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^2.1.7

