name: datahub
description: DataHub is a Cloud Development Ecosystem aiming to bring the power of Dart into the Cloud.
version: 0.18.0-dev.1
homepage: https://datahubproject.net/
resolution: workspace

environment:
  sdk: ^3.6.0

executables:
  datahub:

dependencies:
  args: ^2.5.0
  boost: ^2.0.0-dev.1
  http: ^1.0.0
  http2: ^2.0.0
  intl: ^0.20.0
  path: ^1.8.2
  pointycastle: ^4.0.0
  rxdart: ^0.28.0
  uuid: ^4.4.0
  yaml: ^3.1.1
  # flutter_test depends on test_api: 0.7.0, so 1.25.2 is max version for now
  test: ^1.25.2
  protobuf: ^4.0.0
  fixnum: ^1.1.0
  stack_trace: ^1.11.1
  grpc: ^4.1.0

dev_dependencies:
  datahub_codegen: 0.18.0-dev.1
  lints: ^6.0.0
  build_runner: ^2.7.0

false_secrets:
  - test/resource_hub/localhost.crt
  - test/resource_hub/localhost.key
