# Site Configuration
titleBase: DataHub
favicon: favicon.ico

# Social media links
social:
  - name: Github
    url: https://github.com/christian-thiele/datahub

topNavigation:
  title: DataHub
  links:
    - title: Home
      url: /
    - title: Products
      url: /
    - title: Features
      url: /
    - title: Pricing
      url: /
    - title: Docs
      url: /docs/