tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-fixed-variant": "#006544",
                "primary": "#3bbffa",
                "primary-dim": "#05a9e3",
                "error-dim": "#d7383b",
                "surface-container": "#0f1930",
                "on-secondary-fixed": "#00452d",
                "tertiary-container": "#888bf7",
                "tertiary": "#9799ff",
                "surface": "#060e20",
                "secondary": "#69f6b8",
                "on-tertiary": "#100980",
                "on-tertiary-fixed": "#060061",
                "tertiary-dim": "#9093ff",
                "on-surface-variant": "#a3aac4",
                "surface-container-high": "#141f38",
                "inverse-on-surface": "#4d556b",
                "on-secondary-container": "#e1ffec",
                "surface-tint": "#3bbffa",
                "surface-container-lowest": "#000000",
                "on-background": "#dee5ff",
                "secondary-fixed": "#69f6b8",
                "error-container": "#9f0519",
                "primary-container": "#22b1ec",
                "on-primary-container": "#002b3d",
                "inverse-surface": "#faf8ff",
                "surface-variant": "#192540",
                "outline-variant": "#40485d",
                "on-primary": "#00374d",
                "surface-dim": "#060e20",
                "secondary-container": "#006c49",
                "on-primary-fixed-variant": "#003a50",
                "on-tertiary-fixed-variant": "#292993",
                "secondary-fixed-dim": "#58e7ab",
                "secondary-dim": "#58e7ab",
                "outline": "#6d758c",
                "on-error": "#490006",
                "on-error-container": "#ffa8a3",
                "on-secondary": "#005a3c",
                "background": "#060e20",
                "on-primary-fixed": "#00121d",
                "tertiary-fixed": "#a7a9ff",
                "primary-fixed-dim": "#05a9e3",
                "tertiary-fixed-dim": "#9799ff",
                "surface-bright": "#1f2b49",
                "surface-container-low": "#091328",
                "on-surface": "#dee5ff",
                "inverse-primary": "#00668b",
                "error": "#ff716c",
                "on-tertiary-container": "#05005f",
                "surface-container-highest": "#192540",
                "primary-fixed": "#2db7f2"
            },
            fontFamily: {
                "headline": ["Poppins"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
}