// Writes the datahub_aperture package version into a Dart constant, so it
// can be reported at runtime (bootstrap) and compiled into the frontend.
//
// Runs as melos version preCommit hook. Run manually after changing the
// version in packages/datahub_aperture/pubspec.yaml by hand.
import 'dart:io';

void main() {
  final pubspec = File('packages/datahub_aperture/pubspec.yaml');
  final version = RegExp(
    r'^version:\s*(\S+)\s*$',
    multiLine: true,
  ).firstMatch(pubspec.readAsStringSync())?.group(1);

  if (version == null) {
    stderr.writeln('Missing "version" in ${pubspec.path}.');
    exit(1);
  }

  File('packages/datahub_aperture/lib/src/version.dart').writeAsStringSync(
    '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
    '// Generated by tool/generate_aperture_version.dart\n'
    '\n'
    '/// The version of the datahub_aperture package.\n'
    "const apertureVersion = '$version';\n",
  );
}
