name: datahub_codegen
description: DataHub Code Generation Lib
version: 0.18.0-dev.4
homepage: https://datahubproject.net
repository: https://github.com/christian-thiele/datahub_codegen
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  boost: ^2.0.0
  build: ^4.0.5
  datahub: '>=0.18.0-dev.1 <1.0.0'
  source_gen: ^4.0.0
