name: datahub_codegen
description: DataHub Code Generation Lib
version: 0.18.0-dev.1
homepage: https://datahubproject.net
repository: https://github.com/christian-thiele/datahub_codegen
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.7.1
  boost: ^2.0.0
  build: ^3.0.2
  datahub: '>=0.18.0-dev.1 <1.0.0'
  source_gen: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.7.0