import 'dart:convert';

import 'package:crypto/crypto.dart';

import 'schema_change.dart';

/// One versioned step of the schema history.
///
/// A migration is stored as a plain `.sql` file whose leading block comment
/// carries the structured description of what it does:
///
/// ```sql
/// /* datahub:migration
/// {
///   "version": 3,
///   "name": "add_person_email",
///   "created": "2026-08-19T09:12:33.000Z",
///   "destructive": false,
///   "review": [],
///   "changes": [ ... ]
/// }
/// */
///
/// ALTER TABLE "public"."person" ADD COLUMN "email" varchar;
/// ```
///
/// The file stays valid SQL, so it can be reviewed in a pull request and run
/// through `psql` if it ever has to be. The [changes] in the header are what
/// makes the history replayable: the next migration is generated by diffing
/// the model against the schema those changes add up to, which is why
/// generating one never needs a database.
final class Migration {
  static const headerMarker = 'datahub:migration';

  final int version;
  final String name;
  final DateTime created;

  /// Whether applying this migration can lose data.
  ///
  /// Applying a destructive migration requires `migration.allowDestructive`.
  final bool destructive;

  /// Reasons this migration cannot be applied as generated.
  ///
  /// A generated migration lists everything that is well defined against an
  /// empty table but not against one that already holds rows - adding a
  /// `NOT NULL` column without a default, for instance. Edit the SQL to handle
  /// it, then empty this list to release the migration.
  final List<String> review;

  /// The structured description of what [sql] does, used for replay.
  final List<SchemaChange> changes;

  /// The statements that are executed, as written in the file.
  final String sql;

  const Migration({
    required this.version,
    required this.name,
    required this.created,
    required this.changes,
    required this.sql,
    this.destructive = false,
    this.review = const [],
  });

  String get id => '${paddedVersion}_$name';

  String get paddedVersion => version.toString().padLeft(4, '0');

  String get fileName => '$id.sql';

  bool get requiresReview => review.isNotEmpty;

  Map<String, dynamic> get header => {
    'version': version,
    'name': name,
    'created': created.toUtc().toIso8601String(),
    'destructive': destructive,
    'review': review,
    'changes': changes.map((e) => e.toJson()).toList(),
  };

  /// Renders the complete file content.
  String render() {
    final json = const JsonEncoder.withIndent('  ').convert(header);
    // A block comment ends at the first `*/`, which could otherwise appear
    // inside a view definition or a default expression. `\/` is a valid JSON
    // escape for `/`, so escaping it here keeps the header parseable without
    // changing a single decoded character.
    final escaped = json.replaceAll('*/', r'*\/');

    return '/* $headerMarker\n$escaped\n*/\n\n${sql.trim()}\n';
  }

  /// The checksum recorded when this migration is applied.
  ///
  /// It covers the whole file, header included, so that neither the SQL that
  /// ran nor the changes it claims to make can be altered afterwards without
  /// being noticed.
  static String checksumOf(String content) =>
      sha256.convert(utf8.encode(content)).toString();

  /// Parses a migration file.
  ///
  /// [source] is only used to make error messages point at the right file.
  factory Migration.parse(String content, {String? source}) {
    final trimmed = content.trimLeft();
    if (!trimmed.startsWith('/*')) {
      throw MigrationFormatException(
        'Migration does not start with a "$headerMarker" header block.',
        source,
      );
    }

    final headerEnd = trimmed.indexOf('*/');
    if (headerEnd < 0) {
      throw MigrationFormatException('Unterminated header block.', source);
    }

    final headerBlock = trimmed.substring(2, headerEnd);
    final markerEnd = headerBlock.indexOf(headerMarker);
    if (markerEnd < 0) {
      throw MigrationFormatException(
        'Header block is not marked with "$headerMarker".',
        source,
      );
    }

    final Map<String, dynamic> header;
    try {
      header =
          jsonDecode(headerBlock.substring(markerEnd + headerMarker.length))
              as Map<String, dynamic>;
    } catch (e) {
      throw MigrationFormatException('Header is not valid JSON: $e', source);
    }

    try {
      return Migration(
        version: header['version'] as int,
        name: header['name'] as String,
        created: DateTime.parse(header['created'] as String),
        destructive: header['destructive'] as bool? ?? false,
        review: (header['review'] as List?)?.cast<String>() ?? const [],
        changes: (header['changes'] as List? ?? const [])
            .map((e) => SchemaChange.fromJson(e as Map<String, dynamic>))
            .toList(),
        sql: trimmed.substring(headerEnd + 2).trim(),
      );
    } on MigrationFormatException {
      rethrow;
    } catch (e) {
      throw MigrationFormatException('Invalid header: $e', source);
    }
  }

  /// Builds a migration from [changes], rendering their SQL.
  factory Migration.ofChanges({
    required int version,
    required String name,
    required List<SchemaChange> changes,
    DateTime? created,
  }) {
    final buffer = StringBuffer();
    for (final change in changes) {
      if (change.reviewReason case final reason?) {
        buffer.writeln('-- REVIEW: $reason');
      }
      for (final statement in change.toSql()) {
        buffer.writeln('${statement.toLiteralString()};');
      }
    }

    return Migration(
      version: version,
      name: name,
      created: created ?? DateTime.timestamp(),
      destructive: changes.any((e) => e.isDestructive),
      review: changes.map((e) => e.reviewReason).nonNulls.toList(),
      changes: changes,
      sql: buffer.toString().trim(),
    );
  }

  @override
  String toString() => id;
}

class MigrationFormatException implements Exception {
  final String message;
  final String? source;

  const MigrationFormatException(this.message, [this.source]);

  @override
  String toString() =>
      'MigrationFormatException${source == null ? '' : ' in $source'}: '
      '$message';
}
