import 'dart:math' as math;

import 'package:boost/boost.dart';
import 'package:datahub/datahub.dart';
import 'package:datahub/test.dart';
import 'package:datahub_aperture/datahub_aperture.dart';

import '../_mock/person.dart';
import '../_utils/test_auth_provider.dart';

void main(List<String> args) => runApp([
  KeyService(),
  MemoryRepositoryService(bean: $Person.bean),
  TestAuthProvider(),
  ApiService(
    routes: [
      const ApertureApi(
        oidcIssuer: Config.value('http://localhost:8081/realms/local-oidc'),
        oidcClientId: Config.value('aperture'),
        resources: [
          ApertureResource(repository: Find<DataRepository<Person>>()),
        ],
      ),
    ],
  ),

  ServiceDelegate(
    initialize: () async {
      final repo = Find<DataRepository<$Person>>().find();

      final firstNames = [
        "James",
        "Mary",
        "John",
        "Patricia",
        "Robert",
        "Jennifer",
        "Michael",
        "Linda",
        "William",
        "Barbara",
        "David",
        "Elizabeth",
        "Richard",
        "Susan",
        "Joseph",
        "Jessica",
        "Thomas",
        "Sarah",
        "Charles",
        "Karen",
        "Christopher",
        "Lisa",
        "Daniel",
        "Nancy",
        "Matthew",
        "Betty",
        "Anthony",
        "Margaret",
        "Mark",
        "Sandra",
        "Donald",
        "Ashley",
        "Steven",
        "Dorothy",
        "Paul",
        "Kimberly",
        "Andrew",
        "Emily",
        "Joshua",
        "Donna",
        "Kenneth",
        "Michelle",
        "Kevin",
        "Carol",
        "Brian",
        "Amanda",
        "George",
        "Melissa",
        "Timothy",
        "Deborah",
        "Ronald",
        "Stephanie",
        "Edward",
        "Rebecca",
        "Jason",
        "Sharon",
        "Jeffrey",
        "Laura",
        "Ryan",
        "Cynthia",
        "Jacob",
        "Kathleen",
        "Gary",
        "Amy",
        "Nicholas",
        "Angela",
        "Eric",
        "Shirley",
        "Jonathan",
        "Anna",
        "Stephen",
        "Brenda",
        "Larry",
        "Pamela",
        "Justin",
        "Emma",
        "Scott",
        "Nicole",
        "Brandon",
        "Helen",
        "Benjamin",
        "Samantha",
        "Samuel",
        "Katherine",
        "Raymond",
        "Christine",
        "Gregory",
        "Debra",
        "Frank",
        "Rachel",
        "Alexander",
        "Carolyn",
        "Patrick",
        "Janet",
        "Jack",
        "Catherine",
        "Dennis",
        "Maria",
        "Jerry",
        "Heather",
      ];

      final lastNames = [
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Jones",
        "Garcia",
        "Miller",
        "Davis",
        "Rodriguez",
        "Martinez",
        "Hernandez",
        "Lopez",
        "Gonzalez",
        "Wilson",
        "Anderson",
        "Thomas",
        "Taylor",
        "Moore",
        "Jackson",
        "Martin",
        "Lee",
        "Perez",
        "Thompson",
        "White",
        "Harris",
        "Sanchez",
        "Clark",
        "Ramirez",
        "Lewis",
        "Robinson",
        "Walker",
        "Young",
        "Allen",
        "King",
        "Wright",
        "Scott",
        "Torres",
        "Nguyen",
        "Hill",
        "Flores",
        "Green",
        "Adams",
        "Nelson",
        "Baker",
        "Hall",
        "Rivera",
        "Campbell",
        "Mitchell",
        "Carter",
        "Roberts",
        "Gomez",
        "Phillips",
        "Evans",
        "Turner",
        "Diaz",
        "Parker",
        "Cruz",
        "Edwards",
        "Collins",
        "Reyes",
        "Stewart",
        "Morris",
        "Morales",
        "Murphy",
        "Cook",
        "Rogers",
        "Gutierrez",
        "Ortiz",
        "Morgan",
        "Cooper",
        "Peterson",
        "Bailey",
        "Reed",
        "Kelly",
        "Howard",
        "Ramos",
        "Kim",
        "Cox",
        "Ward",
        "Richardson",
        "Watson",
        "Brooks",
        "Chavez",
        "Wood",
        "James",
        "Bennett",
        "Gray",
        "Mendoza",
        "Ruiz",
        "Hughes",
        "Price",
        "Alvarez",
        "Castillo",
        "Sanders",
        "Patel",
        "Myers",
        "Long",
        "Ross",
        "Foster",
        "Jimenez",
      ];

      final streets = [
        "Maple Avenue",
        "Oak Street",
        "Cedar Lane",
        "Elm Drive",
        "Pine Road",
        "Sunset Boulevard",
        "Willow Way",
        "Birch Court",
        "River Road",
        "Highland Avenue",
        "Meadow Lane",
        "Forest Drive",
        "Hillside Road",
        "Valley View",
        "Lakeside Drive",
        "Cherry Street",
        "Walnut Avenue",
        "Poplar Street",
        "Spruce Lane",
        "Ash Court",
        "Park Place",
        "Garden Way",
        "Orchard Road",
        "Magnolia Drive",
        "Chestnut Street",
        "Lakeview Avenue",
        "Brookside Lane",
        "Rosewood Drive",
        "Clover Court",
        "Cypress Road",
        "Stonegate Drive",
        "Clearwater Lane",
        "Rolling Hills Road",
        "Foxglove Way",
        "Windmill Court",
        "Harvest Moon Drive",
        "Cobblestone Lane",
        "Whispering Pines Road",
        "Redwood Avenue",
        "Maplewood Drive",
        "Hawthorn Street",
        "Ivy Lane",
        "Dogwood Court",
        "Sycamore Drive",
        "Mulberry Way",
        "Juniper Road",
        "Aspen Court",
        "Hickory Lane",
        "Buttonwood Avenue",
        "Sassafras Street",
      ];

      final cities = [
        "10001 New York",
        "90001 Los Angeles",
        "60601 Chicago",
        "77001 Houston",
        "85001 Phoenix",
        "19101 Philadelphia",
        "78201 San Antonio",
        "92101 San Diego",
        "75201 Dallas",
        "95101 San Jose",
        "73301 Austin",
        "32099 Jacksonville",
        "80201 Denver",
        "98101 Seattle",
        "37201 Nashville",
        "02101 Boston",
        "97201 Portland",
        "89101 Las Vegas",
        "30301 Atlanta",
        "33101 Miami",
      ];

      final r = math.Random();
      int number() => r.nextInt(100) + 1;

      for (var i = 0; i < 1000; i++) {
        await repo.create(
          Person(
            id: 0,
            firstName: firstNames.random,
            lastName: lastNames.random,
            nicknames: ['Test'],
            address: '${streets.random} ${number()}, ${cities.random}',
            homeLocation: Point(wgs84, 13.406856, 52.519623),
          ),
        );
      }
    },
  ),
], arguments: args);
