name: Publish package boost to pub.dev

on:
  push:
    tags:
      - 'release/boost/*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart & Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: melos analyze

      - name: Test
        run: melos test

  publish:
    name: Publish Package
    needs: test
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/boost
