name: Publish package datahub_codegen to pub.dev

on:
  push:
    tags:
      - 'release/datahub_codegen/*'

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish Package
    needs: test
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/datahub_codegen
