name: Publish package datahub_aperture to pub.dev

on:
  push:
    tags:
      - 'release/datahub_aperture/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart & Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart run melos analyze

      - name: Test
        run: dart run melos test

  publish:
    needs: test
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/datahub_aperture
